#!/bin/bash

echo "this is cron"

if [ ! -f $OPENSHIFT_DATA_DIR/last_run ]; then
  touch $OPENSHIFT_DATA_DIR/last_run
fi
if [[ $(find $OPENSHIFT_DATA_DIR/last_run -mmin +5) ]]; then #run every 5 mins
  rm -f $OPENSHIFT_DATA_DIR/last_run
  touch $OPENSHIFT_DATA_DIR/last_run
  source ~/app-root/dependencies/python/virtenv/venv/bin/activate
  python ${OPENSHIFT_REPO_DIR}/wsgi/myproject/manage.py querycharacters
fi
